const sections = [
  {
    title: "1. Nature of Service & SEBI Compliance",
    paragraphs: [
      "Suprem Datatech is strictly a technology and software development company. We create mathematical, rule-based indicators and quantitative charting tools. We are NOT registered with the Securities and Exchange Board of India (SEBI) as an Investment Advisor, Research Analyst, or Portfolio Manager. Because our tools are strictly mathematical algorithms applied to price data, they do not constitute personalized financial advice, stock recommendations, or investment tips. Our software is designed solely for educational, technical analysis, and automation purposes.",
    ],
  },
  {
    title: "2. No Guarantee of Profit",
    paragraphs: [
      "Suprem Datatech indicators are tools, not crystal balls. There is absolutely NO GUARANTEE of profit or freedom from losses. Financial markets (including Nifty, BankNifty, XAUUSD, and cryptocurrencies) are highly volatile and inherently risky. A signal generated by our indicators does not mean a trade will be successful. Past performance of our algorithms, whether simulated, backtested, or live, is not indicative of future results. You are solely responsible for your own trading decisions, risk management, and capital.",
    ],
  },
  {
    title: "3. Intellectual Property & License",
    paragraphs: [
      "All quantitative logic, Pine Script code, indicators, methodologies, and visual interfaces provided by Suprem Datatech remain our exclusive intellectual property. Purchasing a subscription grants you a single-user, non-transferable, limited license to use the tools on your personal TradingView account. You strictly may not:",
    ],
    bullets: [
      "Attempt to reverse-engineer, decompile, or copy the source code of any invite-only script.",
      "Resell, redistribute, rent, or share your access/signals with third parties or public groups.",
      "Use our tools to manage third-party funds commercially without an explicit Enterprise License.",
    ],
    footer:
      "Any violation of these terms will result in immediate termination of your access without a refund, and may lead to legal action.",
  },
  {
    title: "4. Subscription and TradingView Access",
    paragraphs: [
      "Our premium indicators require an active free or paid account on TradingView.com. Upon purchase, access is manually granted to the TradingView username you provide. We are not responsible for delays caused by users providing incorrect usernames. Access is tied to a single username and cannot be transferred between accounts once activated.",
    ],
  },
  {
    title: "5. Platform Limitations & Third-Party APIs",
    paragraphs: [
      "Suprem Datatech is not responsible for any financial losses caused by technical failures. This includes, but is not limited to: TradingView platform outages, delayed chart data, webhook alert failures, broker API disconnections (e.g., Upstox, Zerodha, Binance), or internet connectivity issues. You must actively monitor your automated setups.",
    ],
  },
  {
    title: "6. Limitation of Liability",
    paragraphs: [
      "Under no circumstance shall Suprem Datatech, its founders, developers, or affiliates be held liable for any direct, indirect, incidental, special, or consequential damages (including trading losses, loss of profits, or data) arising from the use of our website, indicators, or educational content. You trade entirely at your own risk.",
    ],
  },
  {
    title: "7. Governing Law",
    paragraphs: [
      "These terms are governed by the laws of India. Any disputes arising from the use of Suprem Datatech's services shall be subject to the exclusive jurisdiction of the courts located in Mumbai, Maharashtra.",
    ],
  },
];

export default function TermsAndConditionsPage() {
  return (
    <section className="relative overflow-hidden">
      <div className="relative mx-auto max-w-7xl px-6 py-20 sm:py-28 lg:px-8">
        <span className="text-xs font-semibold tracking-wider text-emerald-600">
          LEGAL COMPLIANCE
        </span>

        <h1 className="mt-4 text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
          Terms &amp; Conditions
        </h1>


        <div className="mt-8 rounded-2xl border border-lime-200 bg-lime-50 p-6">
          <p className="text-sm leading-relaxed text-slate-700">
            By accessing Suprem Datatech.com or purchasing any service, subscription,
            or indicator from Suprem Datatech, you explicitly acknowledge that you
            have read, understood, and agreed to be bound by these Terms &amp;
            Conditions. If you do not agree, you must immediately cease the
            use of our services.
          </p>
        </div>

        <div className="mt-12 space-y-12">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="text-lg font-bold tracking-tight text-slate-900">
                {section.title}
              </h2>

              {section.paragraphs.map((paragraph, idx) => (
                <p
                  key={idx}
                  className="mt-3 text-sm leading-relaxed text-slate-600"
                >
                  {paragraph}
                </p>
              ))}

              {section.bullets && (
                <ul className="mt-4 space-y-2 pl-1">
                  {section.bullets.map((bullet) => (
                    <li
                      key={bullet}
                      className="flex items-start gap-2 text-sm leading-relaxed text-slate-600"
                    >
                      <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-slate-400" />
                      {bullet}
                    </li>
                  ))}
                </ul>
              )}

              {section.footer && (
                <p className="mt-4 text-sm leading-relaxed text-slate-600">
                  {section.footer}
                </p>
              )}
            </div>
          ))}
        </div>

        <div className="mt-14 rounded-2xl border border-slate-200 bg-slate-50 p-6">
          <p className="text-[11px] font-semibold tracking-wider text-slate-400">
            QUESTIONS REGARDING OUR TERMS?
          </p>
          <p className="mt-2 text-sm text-slate-600">
            Reach out to our compliance desk at{" "}
            <span className="font-semibold text-slate-900">
              info.supremedatatech@gmail.com
            </span>
          </p>
        </div>
      </div>
    </section>
  );
}